scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: /3Dlidar_link
    min_x: -8.0
    max_x: 8.0
    min_y: -5.0
    max_y: 5.0
    min_z: -0.3
    max_z: 3.0